version: '3.8'

services:
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9091:9090'
    environment:
      MINIO_ROOT_USER: 'ROOTUSER'
      MINIO_ROOT_PASSWORD: 'SOME_STRONG_PASSWORD'
    volumes:
      - ./data:/data
    command: ["server", "/data", "--console-address", ":9090"]
